receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["otel-collector:8888"]

exporters:
  otlp:
    endpoint: "http://otel-collector:14317" # or your OTLP receiver's address
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  debug: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp, prometheus]
      processors: []
      exporters: [prometheus, debug]
