// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	go_uuid "github.com/satori/go.uuid"
)

type CommunicationMethod string

const (
	CommunicationMethodRest            CommunicationMethod = "rest"
	CommunicationMethodProtocolBuffers CommunicationMethod = "protocol_buffers"
)

func (e *CommunicationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommunicationMethod(s)
	case string:
		*e = CommunicationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CommunicationMethod: %T", src)
	}
	return nil
}

type NullCommunicationMethod struct {
	CommunicationMethod CommunicationMethod
	Valid               bool // Valid is true if CommunicationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommunicationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CommunicationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommunicationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommunicationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommunicationMethod), nil
}

type LimitationKind string

const (
	LimitationKindBudget       LimitationKind = "budget"
	LimitationKindAvailability LimitationKind = "availability"
	LimitationKindPerformance  LimitationKind = "performance"
	LimitationKindSecurity     LimitationKind = "security"
	LimitationKindFeature      LimitationKind = "feature"
)

func (e *LimitationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LimitationKind(s)
	case string:
		*e = LimitationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LimitationKind: %T", src)
	}
	return nil
}

type NullLimitationKind struct {
	LimitationKind LimitationKind
	Valid          bool // Valid is true if LimitationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLimitationKind) Scan(value interface{}) error {
	if value == nil {
		ns.LimitationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LimitationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLimitationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LimitationKind), nil
}

type OptimizationStatus string

const (
	OptimizationStatusEnqueued OptimizationStatus = "enqueued"
	OptimizationStatusRunning  OptimizationStatus = "running"
	OptimizationStatusExecuted OptimizationStatus = "executed"
	OptimizationStatusFailed   OptimizationStatus = "failed"
	OptimizationStatusCanceled OptimizationStatus = "canceled"
)

func (e *OptimizationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OptimizationStatus(s)
	case string:
		*e = OptimizationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OptimizationStatus: %T", src)
	}
	return nil
}

type NullOptimizationStatus struct {
	OptimizationStatus OptimizationStatus
	Valid              bool // Valid is true if OptimizationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOptimizationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OptimizationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OptimizationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOptimizationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OptimizationStatus), nil
}

type RequestKind string

const (
	RequestKindSync  RequestKind = "sync"
	RequestKindBatch RequestKind = "batch"
)

func (e *RequestKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestKind(s)
	case string:
		*e = RequestKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestKind: %T", src)
	}
	return nil
}

type NullRequestKind struct {
	RequestKind RequestKind
	Valid       bool // Valid is true if RequestKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestKind) Scan(value interface{}) error {
	if value == nil {
		ns.RequestKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestKind), nil
}

type ModelClient struct {
	ID         go_uuid.UUID
	Name       string
	ApiKey     string
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type ModelLimitation struct {
	ID         go_uuid.UUID
	ClientID   go_uuid.UUID
	Kind       LimitationKind
	Value      []byte
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type ModelOptimization struct {
	ID              go_uuid.UUID
	ClientID        go_uuid.UUID
	SelectedCloudID go_uuid.UUID
	Status          OptimizationStatus
	Kind            RequestKind
	StartedAt       pgtype.Timestamp
	EndedAt         pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	ModifiedAt      pgtype.Timestamp
}

type ModelOptimizationWaypoint struct {
	ID             go_uuid.UUID
	OptimizationID go_uuid.UUID
	Latitude       float64
	Longitude      float64
}

type ModelProvider struct {
	ID         go_uuid.UUID
	Name       string
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type ModelProviderCommunication struct {
	ID             go_uuid.UUID
	ProviderID     go_uuid.UUID
	AccessibleWith CommunicationMethod
	Url            string
	CreatedAt      pgtype.Timestamp
	ModifiedAt     pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type ModelProviderConstraintsAndFeatures struct {
	ID                         go_uuid.UUID
	ProviderID                 go_uuid.UUID
	MaxWaypoints               int32
	SupportsAsyncBatchRequests bool
}
