// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClientByApiKey = `-- name: GetClientByApiKey :one
SELECT c.id,
  c.name,
  c.created_at,
  c.modified_at,
  c.deleted_at
FROM clients AS c
WHERE c.api_key = $1 LIMIT 1
`

type GetClientByApiKeyRow struct {
	ID         uuid.UUID
	Name       string
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

func (q *Queries) GetClientByApiKey(ctx context.Context, apiKey string) (GetClientByApiKeyRow, error) {
	row := q.db.QueryRow(ctx, getClientByApiKey, apiKey)
	var i GetClientByApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}
